include: package:lint/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    sort_pub_dependencies: ignore

  exclude:
    - lib/domain/auth/auth_failure.freezed.dart
    - lib/application/auth/auth_bloc.freezed.dart